name: Deploy Steadfast API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.18.0"

      - name: Install dependencies
        run: npm ci

      - name: Setup SSH Agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SERVER_DEPLOY_KEY }}"
          ssh-add -l -E sha256

      - name: Deploy to server
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "Attempting to connect to ${USER}@${HOST}..."
          ssh -o StrictHostKeyChecking=no ${USER}@${HOST} 'echo "SSH connection successful"'

          echo "Copying files..."
          rsync -avz --delete --exclude 'node_modules' --exclude '.git' ./ ${USER}@${HOST}:/root/steadfast-api/

          echo "Executing commands on server..."
          ssh -o StrictHostKeyChecking=no ${USER}@${HOST} '
            set -x
            cd /root/steadfast-api
            echo "Current directory: $(pwd)"
            if ! command -v pm2 &> /dev/null; then
              echo "Installing PM2 globally..."
              npm install -g pm2
            else
              echo "PM2 is already installed."
            fi

            echo "Checking if steadfast_api service is running..."
            if sudo systemctl is-active --quiet steadfast_api.service; then
              echo "Service is running. Restarting..."
              sudo systemctl restart steadfast_api.service
            else
              echo "Service is not running. Starting..."
              sudo systemctl start steadfast_api.service
            fi

            echo "Reloading Supervisor configuration..."
            sudo supervisorctl reread
            sudo supervisorctl update

            echo "Checking if steadfast_api process is running..."
            if sudo supervisorctl status steadfast_api | grep -q "RUNNING"; then
              echo "Process is running. Restarting..."
              sudo supervisorctl restart steadfast_api
            else
              echo "Process is not running. Starting..."
              sudo supervisorctl start steadfast_api
            fi

            echo "Checking if PM2 process exists..."
            if pm2 list | grep -q steadfast_api; then
              echo "PM2 process exists. Restarting..."
              pm2 restart steadfast_api
            else
              echo "PM2 process does not exist. Starting..."
              pm2 start server.js --name steadfast_api
            fi

            echo "Deployment completed."
          '
