name: Deploy Steadfast API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.18.0"

      - name: Install dependencies
        run: npm ci

      - name: Setup SSH Agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SERVER_DEPLOY_KEY }}"
          ssh-add -l -E sha256

      - name: Deploy to server
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "Attempting to connect to ${USER}@${HOST}..."
          ssh -o StrictHostKeyChecking=no ${USER}@${HOST} 'echo "SSH connection successful"'

          echo "Copying files..."
          rsync -avz --delete --exclude 'node_modules' --exclude '.git' ./ ${USER}@${HOST}:/root/steadfast-api/

          echo "Executing commands on server..."
          ssh -o StrictHostKeyChecking=no ${USER}@${HOST} '
            set -x
            cd /root/steadfast-api
            echo "Current directory: $(pwd)"
            echo "Installing PM2 globally..."
            npm install -g pm2
            echo "Stopping PM2 process..."
            pm2 stop steadfast_api || true
            echo "Running npm ci..."
            npm ci --no-audit
            echo "Starting PM2 process..."
            pm2 start server.js --name steadfast_api
            echo "Deployment completed."
          '
